#ifdef BUILD_DLL

#ifndef __DORFY_VISION__DWARF_TILE_H__
#define __DORFY_VISION__DWARF_TILE_H__

#include <string>
#include "DwarfDataGeneral.h"
#include "DwarfMaterial.h"

namespace DwarfFortress {
    namespace Designation {
        enum Enum : dword {
            none,
            generic_remove,
            stair_both,
            channel,
            ramp_up,
            stair_down,
            stair_up,
        };
    }

    namespace Traffic {
        enum Enum : dword {
            normal,
            low,
            high,
            restricted
        };
    }

    namespace BuildingOccupancy {
        enum Enum : dword {
            building_con_destruction,
            building_present,
            building_blocked,
            door_forbidden = 6,
            door_present
        };
    }

    struct TileInfo {
        dword
        liquid_level : 3,
        unknown_3 : 1,
        designation : 3,
        smooth : 1,
        engrave : 1,
        invisible : 1,
        layer_index : 4,
        light : 1,
        subterranean : 1,
        outside : 1,
        region_block_bias : 4,
        lava : 1,
        unknown_22_23 : 2,
        traffic : 2,
        unknown_26_29 : 4,
        stagnant : 1,
        salty : 1;
    };

    struct Occupancy {
        dword
        building : 3,
        creature : 1,
        creature_prone : 1,
        item : 1,
        unknown_6_14 : 9,
        boulder : 1;
    };

    namespace BodyType {
        enum Enum {
            none, // no body except a possible floor
            wall,
            fortification,
            rampup_trivial, // excluding mushroom cap slope
            rampdown,
            stairboth,
            stairdown,
            stairup,
            track,
            trackup,
            shrub,
            sapling,
            tree_trivial,
            tree_rampup,
            pebble,
            boulder
        };
    }

    namespace TreeType {
        enum Enum {
            none,
            root,
            trunk,
            thick_branches,
            branches,
            twigs,
            cap
        };
    }

    namespace GrassType {
        enum Enum {
            none,
            normal_1,
            normal_2,
            dry,
            dead
        };
    }

    namespace TileFeatureType {
        enum Enum {
            none,
            layer_rock,
            layer_soil,
            grass,
            mineral,
            unknown,
            obsidian,
            ice
        };
    }

    struct TileDefinition {
        byte
        hasbase : 1, // downward stairway
        hasfloor : 1,
        isblocked : 1,
        isupslope : 1, // including mushroom cap slope
        bodytype : 4,
        isalive : 1,
        hasconnection : 1,
        treetype : 3,
        grasstype : 3,
        tilefeaturetype : 3,
        templatecolortype : 3;
        struct Connection {
            byte
            north : 2, // 0 = none, 1 = thin, 2 = thick, 3 = full
            south : 2,
            west : 2,
            east : 2;
        } connection;
    };
    static_assert(sizeof(TileDefinition) == 4, "");

    namespace TileStructure {
        enum Enum : word {
            none = 0x0000,
            downward_slope,
            murky_pool,
            murky_pool_slope_up,
            underworld_gate_up,
            underworld_gate_down,
            underworld_gate_both,
            driftwood = 0x0013,
            ice_stair_both = 0x0019,
            ice_stair_down,
            ice_stair_up,
            open_space = 0x0020,
            shrub = 0x0022,
            chasm,
            obsidian_stair_both = 0x0024,
            obsidian_stair_down,
            obsidian_stair_up,
            soil_stair_both,
            soil_stair_down,
            soil_stair_up,
            eerie_glowing_pit,
            smooth_layer_floor,
            smooth_obsidian_floor,
            smooth_unknown_floor,
            smooth_mineral_floor,
            level_ice_floor,
            grass_2_stair_both = 0x0031,
            grass_2_stair_down,
            grass_2_stair_up,
            grass_1_stair_both,
            grass_1_stair_down,
            grass_1_stair_up,
            layer_stair_both,
            layer_stair_down,
            layer_stair_up,
            mineral_stair_both,
            mineral_stair_down,
            mineral_stair_up,
            unknown_stair_both,
            unknown_stair_down,
            unknown_stair_up,
            layer_fortification = 0x0041,
            ashes_floor_campfire = 0x0043,
            ashes_floor_burning_1 = 0x0046,
            ashes_trunk_burning,
            ashes_branches_burning,
            ashes_twigs_burning,
            ashes_double_exclaimation_burning,
            ashes_up_triangle_burning,
            ashes_floor_burning_2,
            layer_pillar = 0x004F,
            obsidian_pillar,
            unknown_pillar,
            mineral_pillar,
            ice_pillar,
            waterfall = 0x0059,
            river_source,
            tree_root_vertical_end,
            tree_root,
            tree_trunk_pillar,
            tree_trunk_vertical_end,
            tree_trunk_bark_N,
            tree_trunk_bark_S,
            tree_trunk_bark_E,
            tree_trunk_bark_W,
            tree_trunk_SE,
            tree_trunk_SW,
            tree_trunk_NE,
            tree_trunk_NW,
            tree_trunk_WEn,
            tree_trunk_WEs,
            tree_trunk_NSe,
            tree_trunk_NSw,
            tree_thick_branches_ns,
            tree_thick_branches_we,
            tree_branches_smooth,
            dead_tree_branches_smooth,
            tree_thick_branches_nw,
            tree_thick_branches_ne,
            tree_thick_branches_sw,
            tree_thick_branches_se,
            tree_branches,
            tree_twigs,
            cap_slope_up,
            cap_pith,
            cap_N,
            cap_S,
            cap_E,
            cap_W,
            cap_SE,
            cap_SW,
            cap_NE,
            cap_NW,
            cap_pointed_1,
            cap_pointed_2,
            cap_pointed_3,
            cap_pointed_4,
            dead_tree_root_vertical_end,
            dead_tree_root,
            dead_tree_trunk_pillar,
            dead_tree_trunk_vertical_end,
            dead_tree_trunk_bark_N,
            dead_tree_trunk_bark_S,
            dead_tree_trunk_bark_E,
            dead_tree_trunk_bark_W,
            dead_tree_trunk_SE,
            dead_tree_trunk_SW,
            dead_tree_trunk_NE,
            dead_tree_trunk_NW,
            dead_tree_trunk_WEn,
            dead_tree_trunk_WEs,
            dead_tree_trunk_NSe,
            dead_tree_trunk_NSw,
            dead_tree_thick_branches_ns,
            dead_tree_thick_branches_we,
            dead_tree_thick_branches_nw = 0x0097,
            dead_tree_thick_branches_ne,
            dead_tree_thick_branches_sw,
            dead_tree_thick_branches_se,
            dead_tree_branches,
            dead_tree_twigs,
            dead_cap_slope_up,
            dead_cap_pith,
            dead_cap_N,
            dead_cap_S,
            dead_cap_E,
            dead_cap_W,
            dead_cap_SE,
            dead_cap_SW,
            dead_cap_NE,
            dead_cap_NW,
            dead_cap_dot_1,
            dead_cap_dot_2,
            dead_cap_dot_3,
            dead_cap_dot_4,
            layer_wall_mined_3 = 0xAC,
            layer_wall_mined_2,
            layer_wall_mined_1,
            tree_thick_branches_nse,
            tree_thick_branches_nsw,
            tree_thick_branches_wen,
            tree_thick_branches_wes,
            tree_thick_branches_nswe,
            dead_tree_thick_branches_nse,
            dead_tree_thick_branches_nsw,
            dead_tree_thick_branches_wen,
            dead_tree_thick_branches_wes,
            dead_tree_thick_branches_nswe,
            tree_trunk_NSE,
            tree_trunk_NSW,
            tree_trunk_WEN,
            tree_trunk_WES,
            tree_trunk_NS,
            tree_trunk_WE,
            tree_trunk_NSWE,
            tree_trunk_pith,
            dead_tree_trunk_NSE,
            dead_tree_trunk_NSW,
            dead_tree_trunk_WEN,
            dead_tree_trunk_WES,
            dead_tree_trunk_NS,
            dead_tree_trunk_WE,
            dead_tree_trunk_NSWE,
            dead_tree_trunk_pith,
            layer_wall = 0x00D7,
            sapling = 0x00E3,
            dry_grass_slope_up = 0x00E5,
            dead_grass_slope_up,
            grass_2_slope_up,
            grass_1_slope_up,
            layer_slope_up,
            obsidian_slope_up,
            unknown_slope_up,
            mineral_slope_up,
            soil_slope_up,
            ashes_floor_burnt_1, // >
            ashes_floor_burnt_2, // <
            ashes_floor_burnt_3, // ~
            glacial_slope_up,
            ice_floor_1 = 0x00FE,
            ice_floor_2,
            ice_floor_3,
            furrowed_soil_floor,
            ice_floor_4,
            semi_molten_rock,
            lava_flow,
            soil_wall,
            glowing_barrier,
            glowing_floor,
            smooth_obsidian_wall_Se = 0x0109,
            smooth_obsidian_wall_sE,
            smooth_obsidian_wall_nE,
            smooth_obsidian_wall_Ne,
            smooth_obsidian_wall_nW,
            smooth_obsidian_wall_Nw,
            smooth_obsidian_wall_sW,
            smooth_obsidian_wall_Sw,
            smooth_obsidian_wall_NSWE,
            smooth_obsidian_wall_NSE,
            smooth_obsidian_wall_WES,
            smooth_obsidian_wall_WEN,
            smooth_obsidian_wall_NSW,
            smooth_obsidian_wall_SE,
            smooth_obsidian_wall_NE,
            smooth_obsidian_wall_NW,
            smooth_obsidian_wall_SW,
            smooth_obsidian_wall_NS,
            smooth_obsidian_wall_WE,
            smooth_unknown_wall_Se,
            smooth_unknown_wall_sE,
            smooth_unknown_wall_nE,
            smooth_unknown_wall_Ne,
            smooth_unknown_wall_nW,
            smooth_unknown_wall_Nw,
            smooth_unknown_wall_sW,
            smooth_unknown_wall_Sw,
            smooth_unknown_wall_NSWE,
            smooth_unknown_wall_NSE,
            smooth_unknown_wall_WES,
            smooth_unknown_wall_WEN,
            smooth_unknown_wall_NSW,
            smooth_unknown_wall_SE,
            smooth_unknown_wall_NE,
            smooth_unknown_wall_NW,
            smooth_unknown_wall_SW,
            smooth_unknown_wall_NS,
            smooth_unknown_wall_WE,
            smooth_layer_wall_Se,
            smooth_layer_wall_sE,
            smooth_layer_wall_nE,
            smooth_layer_wall_Ne,
            smooth_layer_wall_nW,
            smooth_layer_wall_Nw,
            smooth_layer_wall_sW,
            smooth_layer_wall_Sw,
            smooth_layer_wall_NSWE,
            smooth_layer_wall_NSE,
            smooth_layer_wall_WES,
            smooth_layer_wall_WEN,
            smooth_layer_wall_NSW,
            smooth_layer_wall_SE,
            smooth_layer_wall_NE,
            smooth_layer_wall_NW,
            smooth_layer_wall_SW,
            smooth_layer_wall_NS,
            smooth_layer_wall_WE,
            obsidian_fortification,
            unknown_fortification,
            obsidian_wall_mined_3,
            obsidian_wall_mined_2,
            obsidian_wall_mined_1,
            obsidian_wall,
            unknown_wall_mined_3,
            unknown_wall_mined_2,
            unknown_wall_mined_1,
            unknown_wall,
            layer_floor_1, //'
            layer_floor_2, //,
            layer_floor_3, //`
            layer_floor_4, //.
            obsidian_floor_1,
            obsidian_floor_2,
            obsidian_floor_3,
            obsidian_floor_4,
            unknown_floor_1,
            unknown_floor_2,
            unknown_floor_3,
            unknown_floor_4,
            grass_1_floor_1,
            grass_1_floor_2,
            grass_1_floor_3,
            grass_1_floor_4,
            soil_floor_1,
            soil_floor_2,
            soil_floor_3,
            soil_floor_4,
            wet_soil_floor_1,
            wet_soil_floor_2,
            wet_soil_floor_3,
            wet_soil_floor_4,
            ice_fortification,
            ice_wall_mined_3,
            ice_wall_mined_2,
            ice_wall_mined_1,
            ice_wall,
            river_1,
            river_2,
            river_3,
            river_4,
            river_5,
            river_6,
            river_7,
            river_8,
            brook_1,
            brook_2,
            brook_3,
            brook_4,
            brook_5,
            brook_6,
            brook_7,
            brook_8,
            brook_surface,
            dry_grass_floor_1 = 0x017F,
            dry_grass_floor_2,
            dry_grass_floor_3,
            dry_grass_floor_4,
            dead_sapling = 0x0184,
            dead_shrub,
            dead_grass_floor_1,
            dead_grass_floor_2,
            dead_grass_floor_3,
            dead_grass_floor_4,
            grass_2_floor_1,
            grass_2_floor_2,
            grass_2_floor_3,
            grass_2_floor_4,
            layer_boulder,
            obsidian_boulder,
            unknown_boulder,
            layer_pebbles_1,
            layer_pebbles_2,
            layer_pebbles_3,
            layer_pebbles_4,
            obsidian_pebbles_1,
            obsidian_pebbles_2,
            obsidian_pebbles_3,
            obsidian_pebbles_4,
            unknown_pebbles_1,
            unknown_pebbles_2,
            unknown_pebbles_3,
            unknown_pebbles_4,
            smooth_mineral_wall_Se,
            smooth_mineral_wall_sE,
            smooth_mineral_wall_nE,
            smooth_mineral_wall_Ne,
            smooth_mineral_wall_nW,
            smooth_mineral_wall_Nw,
            smooth_mineral_wall_sW,
            smooth_mineral_wall_Sw,
            smooth_mineral_wall_NSWE,
            smooth_mineral_wall_NSE,
            smooth_mineral_wall_WES,
            smooth_mineral_wall_WEN,
            smooth_mineral_wall_NSW,
            smooth_mineral_wall_SE,
            smooth_mineral_wall_NE,
            smooth_mineral_wall_NW,
            smooth_mineral_wall_SW,
            smooth_mineral_wall_NS,
            smooth_mineral_wall_WE,
            mineral_fortification,
            mineral_wall_mined_3,
            mineral_wall_mined_2,
            mineral_wall_mined_1,
            mineral_wall,
            mineral_floor_1,
            mineral_floor_2,
            mineral_floor_3,
            mineral_floor_4,
            mineral_boulder,
            mineral_pebbles_1,
            mineral_pebbles_2,
            mineral_pebbles_3,
            mineral_pebbles_4,
            straight_ice_wall_Se,
            straight_ice_wall_sE,
            straight_ice_wall_nE,
            straight_ice_wall_Ne,
            straight_ice_wall_nW,
            straight_ice_wall_Nw,
            straight_ice_wall_sW,
            straight_ice_wall_Sw,
            straight_ice_wall_NSWE,
            straight_ice_wall_NSE,
            straight_ice_wall_WES,
            straight_ice_wall_WEN,
            straight_ice_wall_NSW,
            straight_ice_wall_SE,
            straight_ice_wall_NE,
            straight_ice_wall_NW,
            straight_ice_wall_SW,
            straight_ice_wall_NS,
            straight_ice_wall_WE,
            river_slope_up_1,
            river_slope_up_2, //generated
            river_slope_up_3,
            river_slope_up_4,
            river_slope_up_5,
            river_slope_up_6,
            river_slope_up_7,
            river_slope_up_8,
            constructed_floor = 0x01E9,
            constructed_fortification,
            constructed_pillar,
            constructed_wall_Se,
            constructed_wall_sE,
            constructed_wall_nE,
            constructed_wall_Ne,
            constructed_wall_nW,
            constructed_wall_Nw,
            constructed_wall_sW,
            constructed_wall_Sw,
            constructed_wall_NSWE,
            constructed_wall_NSE,
            constructed_wall_WES,
            constructed_wall_WEN,
            constructed_wall_NSW,
            constructed_wall_SE,
            constructed_wall_NE,
            constructed_wall_NW,
            constructed_wall_SW,
            constructed_wall_NS,
            constructed_wall_WE,
            constructed_stair_both,
            constructed_stair_down,
            constructed_stair_up,
            constructed_slope_up,
            layer_track_N,
            layer_track_S,
            layer_track_E,
            layer_track_W,
            layer_track_NS,
            layer_track_NE,
            layer_track_NW,
            layer_track_SE,
            layer_track_SW,
            layer_track_EW,
            layer_track_NSE,
            layer_track_NSW,
            layer_track_NEW,
            layer_track_SEW,
            layer_track_NSEW,
            obsidian_track_N,
            obsidian_track_S,
            obsidian_track_E,
            obsidian_track_W,
            obsidian_track_NS,
            obsidian_track_NE,
            obsidian_track_NW,
            obsidian_track_SE,
            obsidian_track_SW,
            obsidian_track_EW,
            obsidian_track_NSE,
            obsidian_track_NSW,
            obsidian_track_NEW,
            obsidian_track_SEW,
            obsidian_track_NSEW,
            unknown_track_N,
            unknown_track_S,
            unknown_track_E,
            unknown_track_W,
            unknown_track_NS,
            unknown_track_NE,
            unknown_track_NW,
            unknown_track_SE,
            unknown_track_SW,
            unknown_track_EW,
            unknown_track_NSE,
            unknown_track_NSW,
            unknown_track_NEW,
            unknown_track_SEW,
            unknown_track_NSEW,
            mineral_track_N,
            mineral_track_S,
            mineral_track_E,
            mineral_track_W,
            mineral_track_NS,
            mineral_track_NE,
            mineral_track_NW,
            mineral_track_SE,
            mineral_track_SW,
            mineral_track_EW,
            mineral_track_NSE,
            mineral_track_NSW,
            mineral_track_NEW,
            mineral_track_SEW,
            mineral_track_NSEW,
            ice_track_N,
            ice_track_S,
            ice_track_E,
            ice_track_W,
            ice_track_NS,
            ice_track_NE,
            ice_track_NW,
            ice_track_SE,
            ice_track_SW,
            ice_track_EW,
            ice_track_NSE,
            ice_track_NSW,
            ice_track_NEW,
            ice_track_SEW,
            ice_track_NSEW,
            constructed_track_N,
            constructed_track_S,
            constructed_track_E,
            constructed_track_W,
            constructed_track_NS,
            constructed_track_NE,
            constructed_track_NW,
            constructed_track_SE,
            constructed_track_SW,
            constructed_track_EW,
            constructed_track_NSE,
            constructed_track_NSW,
            constructed_track_NEW,
            constructed_track_SEW,
            constructed_track_NSEW,
            layer_track_up_N,
            layer_track_up_S,
            layer_track_up_E,
            layer_track_up_W,
            layer_track_up_NS,
            layer_track_up_NE,
            layer_track_up_NW,
            layer_track_up_SE,
            layer_track_up_SW,
            layer_track_up_EW,
            layer_track_up_NSE,
            layer_track_up_NSW,
            layer_track_up_NEW,
            layer_track_up_SEW,
            layer_track_up_NSEW,
            obsidian_track_up_N,
            obsidian_track_up_S,
            obsidian_track_up_E,
            obsidian_track_up_W,
            obsidian_track_up_NS,
            obsidian_track_up_NE,
            obsidian_track_up_NW,
            obsidian_track_up_SE,
            obsidian_track_up_SW,
            obsidian_track_up_EW,
            obsidian_track_up_NSE,
            obsidian_track_up_NSW,
            obsidian_track_up_NEW,
            obsidian_track_up_SEW,
            obsidian_track_up_NSEW,
            unknown_track_up_N,
            unknown_track_up_S,
            unknown_track_up_E,
            unknown_track_up_W,
            unknown_track_up_NS,
            unknown_track_up_NE,
            unknown_track_up_NW,
            unknown_track_up_SE,
            unknown_track_up_SW,
            unknown_track_up_EW,
            unknown_track_up_NSE,
            unknown_track_up_NSW,
            unknown_track_up_NEW,
            unknown_track_up_SEW,
            unknown_track_up_NSEW,
            mineral_track_up_N,
            mineral_track_up_S,
            mineral_track_up_E,
            mineral_track_up_W,
            mineral_track_up_NS,
            mineral_track_up_NE,
            mineral_track_up_NW,
            mineral_track_up_SE,
            mineral_track_up_SW,
            mineral_track_up_EW,
            mineral_track_up_NSE,
            mineral_track_up_NSW,
            mineral_track_up_NEW,
            mineral_track_up_SEW,
            mineral_track_up_NSEW,
            ice_track_up_N,
            ice_track_up_S,
            ice_track_up_E,
            ice_track_up_W,
            ice_track_up_NS,
            ice_track_up_NE,
            ice_track_up_NW,
            ice_track_up_SE,
            ice_track_up_SW,
            ice_track_up_EW,
            ice_track_up_NSE,
            ice_track_up_NSW,
            ice_track_up_NEW,
            ice_track_up_SEW,
            ice_track_up_NSEW,
            constructed_track_up_N,
            constructed_track_up_S,
            constructed_track_up_E,
            constructed_track_up_W,
            constructed_track_up_NS,
            constructed_track_up_NE,
            constructed_track_up_NW,
            constructed_track_up_SE,
            constructed_track_up_SW,
            constructed_track_up_EW,
            constructed_track_up_NSE,
            constructed_track_up_NSW,
            constructed_track_up_NEW,
            constructed_track_up_SEW,
            constructed_track_up_NSEW,
            structure_end
        };
    }

    void tileDefinitionInit();
    TileDefinition const tileDefinition(TileStructure::Enum structure);
}

#endif

#endif
